### PR TITLE
Distribution statistics

### PR DESCRIPTION
**Pull request by luisfabib**
See #33

### CODE REVIEW

**Comment by stestoll** [comment]
I think this is an important function. A few points:
- If a distribution has multiple modes, `modes` should return them all. E.g. if `modality`is 2, `modes` should contain two numbers. There could be two mode outputs: `modes` returns all modes, and `mode` returns the first mode. This is how it's done in [Julia's Distribution package](https://juliastats.org/Distributions.jl/stable/univariate/#StatsBase.modes-Tuple{Distribution{Univariate,S}%20where%20S%3C:ValueSupport}).
- Maybe an optional argument that specifies the particular descriptor that is requested, e.g. `distdescr(r,P,Puq,'mean')`
- The threshold for peak finding is hard-wired, that's not ideal. Maybe add an optional keyword argument to modify that value.
- There are two different definitions of `kurtosis`, one as the fourth moment, and the other the fourth moment minus 3. The latter is called excess kurtosis, and some take that as the default definition. We need to decide what to do. Both [SciPy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html) and [Julia's StatsBase](https://juliastats.org/StatsBase.jl/v0.21/scalarstats.html#StatsBase.kurtosis) provide excess kurtosis by default.
- I think `range` should be broken up into `min` and `max`.
- I wonder whether it makes more sense to put `r` as the first input and `P` as the second. What the function is calculating is actually statistics of `r` (over the `P`), and not of `P`.  
- Should the integral also be included as a descriptor (for shape).
- Add entropy!
- Maybe add central moments `moment1`, `moment2`, `moment3`, `moment4`, etc. This would duplicate some numbers, but it would be easier for users that are less familiar with all the stats terms.

**Comment by stestoll** [comment]
`diststats` (distance statistics) might be a better name than `distdesc`.

**Comment by luisfabib** [comment]
Yes, that's a better name.

**Comment by luisfabib** [comment]
Regarding a couple of @stestoll comments: 

> Should the integral also be included as a descriptor (for shape)

I do not understand what you mean by the integral. Do you mean the cumulative sum over the distribution? Otherwise the integral should be normalized to unity and hence the same for all distributions.


>  I think range should be broken up into min and max.

I do not know it is necessary to even have `range` as a descriptor. Actually `range` is only being printed but not included into the output dictionaries.

**Comment by stestoll** [comment]
The minimum and the maximum of the support of a probability distribution are basic statistical quantities, so should be included, at least in principle. It doesn't hurt including them, It emphasizes that all distributions in DeerLab are truncated.

The integral is equal to the zeroth moment, so it's also a statistical descriptor. iIt might not be very useful to include it. The only use would be that the user calls `diststats(r,P,'int')` to calculate the integral without having to do it manually. All DeerLab distributions are normalizes, but the user might want to use `diststats` on uiser-defined distributions, e.g. obtained from structural modeling.

**Review by stestoll — APPROVED** [review]

**Pull request merged**
