### PR TITLE
Update version and changelog

### PR DESCRIPTION
**Pull request by luisfabib**

### CODE REVIEW

**Review by stestoll — CHANGES_REQUESTED** [review]
I think we need to address #76 in this release.

**Comment by stestoll** [comment]
Also, shouldn't VERSION be set to 0.14-dev?

**Comment by luisfabib** [comment]
Not is should not. The PyPI version is taken from VERSION upon release. The current release workflow is: 

       Bump to release VERSION --> Release on GitHub w/ new tag --> Upload to PyPI --> Bumb to dev VERSION

**Comment by stestoll** [comment]
The update to CHANGELOG should be in the dev version in the main branch (which is 0.13-dev now). We should actually update it as we add to the main branch. Then, for a release, we just change 0.13-dev to 0.13.

**Pull request merged**
